language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
    - py.test
after_success:
    - coveralls